
# SEO settings
title: "X"
description: "发现有趣的事情～"
keywords: "novel"
url: httt://blog.okuer.com # site url
# baseurl: "/" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/xxlv/okuer
disqus_shortname: "heiswayi"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Ghost"
  job      : "Software Engineer"
  bio      : ""
  thumb    : /images/author.jpg
  email    : lvxiang119@gmail.com
  url      : http://heiswayi.github.io

# social settings
# og_locale: "en_US"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

plugins:
  - bourbon
  - jekyll-paginate
  - jekyll-plantuml

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]

# theme: jekyll-theme-merlot
