# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "愤怒的小白"
email: lvxiang119@gmail.com
description: > # this means to ignore newlines until "baseurl:
"科技,哲学,生活,故事"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.okuer.com" # the base hostname & protocol for your site
github_username:  xxlv

# Build settings
markdown: kramdown